import Foundation

@objc
public enum PushError: Int {
    case none
    case apnProcessing
    case apnMissingDeviceToken
    case apnMissingTopic
    case apnMissingPayload
    case apnInvalidTokenSize
    case apnInvalidTopicSize
    case apnInvalidPayloadSize
    case apnInvalidTokenContent
    case apnUnknownReason
    case apnShutdown
    case apnUnknownErrorCode
    case pushResponseCommand
    case pushNotConnected
    case pushWriteFail
    case feedbackLength
    case feedbackTokenLength
    case socketCreate
    case socketConnect
    case socketResolveHostName
    case socketFileControl
    case socketOptions
    case sslConnection
    case sslContext
    case sslIOFuncs
    case sslPeerDomainName
    case sslCertificate
    case sslDroppedByServer
    case sslAuthFailed
    case sslHandshakeFail
    case sslHandshakeUnknownRootCert
    case sslHandshakeNoRootCert
    case sslHandshakeCertExpired
    case sslHandshakeXCertChainInvalid
    case sslHandshakeClientCertRequested
    case sslHandshakeServerAuthCompleted
    case sslHandshakePeerCertExpired
    case sslHandshakePeerCertRevoked
    case sslHandshakePeerCertUnknown
    case sslHandshakeInternalError
    case sslInDarkWake
    case sslHandshakeClosedAbort
    case sslHandshakeTimeout
    case readDroppedByServer
    case readClosedAbort
    case readClosedGraceful
    case readFail
    case writeDroppedByServer
    case writeClosedAbort
    case writeClosedGraceful
    case writeFail
    case identityCopyCertificate
    case identityCopyPrivateKey
    case pkcs12Import
    case pkcs12EmptyData
    case pkcs12Decode
    case pkcs12AuthFailed
    case pkcs12Password
    case pkcs12PasswordRequired
    case pkcs12NoItems
    case pkcs12MultipleItems
    case keychainCopyMatching
    case keychainItemNotFound
    case keychainCreateIdentity
}
